[nfs]
172.31.82.132 ansible_ssh_user='ec2-user'

[webservers]
172.31.91.26   ansible_ssh_user='ec2-user'
<172.31.85.240 ansible_ssh_user='ec2-user'

[db]
172.31.81.23 ansible_ssh_user='ubuntu' 

[lb]
172.31.89.27 ansible_ssh_user='ubuntu'